### ISSUE TITLE
Resource Busy or Locked When Exporting PDF Items

### ISSUE THREAD

**Issue by hp6393** [tropy/tropy-plugin-archive#4]
Exported two JPEG files to a Zip file. Worked fine. No errors.

Exported two PDF files to a Zip file. Followed same steps as JPEG. Received the following error:

> {"msg":"Failed to export items.","stack":"Error: EBUSY: resource busy or locked, copyfile 'C:\\temp\\test1.pdf' -> 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\tropy-archive-ejXuUt\\tropy\\test1.pdf'","system":"Windows_NT 10.0.19043 (x64)","time":1647929348807,"version":"1.11.1"}

I then tried exploding the PDFs and then exporting them as images. Received the same error as above.

**Comment by inukshuk** [comment]
This means that the file can't be copied to the temporary directory prior to creating the Zip file. Can you think of a reason why Tropy would not have read-access to the PDF at that moment? Perhaps the PDF is currently opened by a different application or something like that?

**Comment by caro401** [comment]
This issue should be fixed in the [latest release](https://github.com/tropy/tropy-plugin-archive/releases/latest) - @hp6393 could you confirm whether this resolves your issue?

**Comment by hp6393** [comment]
Sorry for the delay. Was away last week. Yes, I just tested the 3.1.1 and the error is resolved. Thanks!
